[package]
name = "duplicate-finder"
version = "0.1.0"
description = "Findet doppelte Dateien per MD5-Prüfsumme und verschiebt sie, statt sie zu löschen"
authors = ["Mario Mohar <iam@themo.at>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Mario-Mohar/Duplikat-Filesorter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "duplicate_finder_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
md5 = "0.7"
chrono = "0.4"

